name: CI

on:
  push:
    branches:
      - main
      - 'dependabot/**'
  pull_request:
    branches:
      - '**'

jobs:
  lint:
    uses: stylelint/.github/.github/workflows/lint.yml@restrict-permissions-and-run-only-test

  test:
    uses: stylelint/.github/.github/workflows/test.yml@restrict-permissions-and-run-only-test
    with:
      os: '["ubuntu-latest", "windows-latest", "macos-latest"]'
